
version: 0.0.{build}
platform: x64

install:
  - cinst 7zip
  - ps: Install-Module psake
  - ps: Install-Module pester

before_build:
  - ps: Invoke-psake ? -properties @{"version"="$Env:APPVEYOR_BUILD_VERSION";"zip_cmd"="7z"}

build_script:
  - ps: Invoke-psake -Verbose -taskList Build, Assemble -properties @{"version"="$Env:APPVEYOR_BUILD_VERSION";"zip_cmd"="7z"}

test_script:
  - ps: Invoke-psake -Verbose InlineTest -properties @{"version"="$Env:APPVEYOR_BUILD_VERSION";"zip_cmd"="7z"}

artifacts:
  - path: ./out/*.zip

deploy:
  release: devpack-v$(APPVEYOR_BUILD_VERSION)
  description: 'full devpack'
  provider: GitHub
  auth_token:
    secure: McXn11nJ4l06C283bftRirmxi8bEa2exPp3JfCaVfipZUZ5IUU6570Y6Y0CwKkEu
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: false  # release all master commits

# building tags triggers an infinite loop from github release tags
skip_tags: true
