
version: 0.0.{build}
platform: x64

install:
  - cinst 7zip
  - ps: Install-Module psake
  - ps: Install-Module pester

before_build:
  - ps: Invoke-psake ? -properties @{"version"="$Env:APPVEYOR_BUILD_VERSION";"zip_cmd"="7z"}

build_script:
  - ps: Invoke-psake -Verbose -taskList Build, Assemble -properties @{"version"="$Env:APPVEYOR_BUILD_VERSION";"zip_cmd"="7z"}

test_script:
  - ps: Invoke-psake -Verbose InlineTest -properties @{"version"="$Env:APPVEYOR_BUILD_VERSION";"zip_cmd"="7z"}

artifacts:
  - path: ./out/*.zip

# building tags triggers an infinite loop from github release tags
skip_tags: true
